name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shubhindia
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Kolkata
          config_twemoji: yes

          # Activities plugin
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B

          # People plugin
          plugin_people: yes
          plugin_people_limit: 50
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
